2025-02-14 16:21:18,297-ERROR,filename E:\Healthcare\Healtcare\dpconfig.py,and line number 54,and error class <class 'mysql.connector.errors.DatabaseError'>
